In [25]:
# taking images from camera
import cv2
cap = cv2.VideoCapture(0)

def testVideoCam():
    while True:
        has_frame, frame = cap.read()
        if not has_frame:
            print('No frames are captured')
            break
        #frame = cv2.resize(frame,(160,160))
        cv2.imshow('testFrame',frame)
        key = cv2.waitKey(3)
        if key == 27:
            print('Pressed Esc')
            break
    cap.release()
    cv2.destroyAllWindows()
    return

#testVideoCam()

#capture image for training
for i in range(10):
    has_frame, frame = cap.read()
    if not has_frame:
        print('No frames are captured')
    #frame = cv2.resize(frame,(160,160))
    
cv2.imshow('testFrame',frame)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [26]:
#saving the trainImage
filepath = "C:\\FaceRecognitionFiles\\"
cv2.imwrite(filepath+'trainImage.jpg',frame)

True

In [39]:
#detect face from saved trainImage
from PIL import Image
from mtcnn.mtcnn import MTCNN
import numpy as np
import matplotlib.pyplot as plt
detector = MTCNN()

In [28]:
trainface_metadata = detector.detect_faces(frame) #extracting faces from trainImage

1/1 [==============================] - 0s 221ms/step


In [29]:
print('number of faces detected = ', len(trainface_metadata))

number of faces detected =  1


In [30]:
print(trainface_metadata[0])

{'box': [300, 150, 142, 176], 'confidence': 0.999784529209137, 'keypoints': {'left_eye': (337, 215), 'right_eye': (402, 208), 'nose': (372, 244), 'mouth_left': (352, 286), 'mouth_right': (404, 281)}}


In [31]:
#detecting face coordinates
x = int(trainface_metadata[0]['box'][0])
y = int(trainface_metadata[0]['box'][1])
w = int(trainface_metadata[0]['box'][2])
h = int(trainface_metadata[0]['box'][3])

detected_face = cv2.rectangle(frame, (x,y),(x+w,y+h), color=255, thickness=3) #see the detected face outlines
cv2.imshow('Detected face with rectangle',detected_face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
#cropping the image to required size 160,160
face = frame[y:y+h, x:x+w]
face = Image.fromarray(face)
face = face.resize((160,160))
face = np.asarray(face)

In [42]:
#display cropped image
cv2.imshow('Cropped image', face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
#create face embedding
import tensorflow as tf
from keras_facenet import FaceNet
embedder = FaceNet()

In [46]:
#face embedding generator function
def get_embedding_facenet(face_pixels):
    face_pixels = face_pixels.astype('float32')
    mean, std = face_pixels.mean(), face_pixels.std()
    face_pixels = (face_pixels - mean)/std
    samples = np.expand_dims(face_pixels, axis=0)
    embedding = embedder.model.predict(samples)
    return embedding[0]

In [47]:
trainface_embedding = get_embedding_facenet(face)

1/1 [==============================] - 2s 2s/step


In [50]:
#printing face embedding
print(trainface_embedding)

[-0.00453827  0.05723704 -0.01597803 -0.00623874  0.08644808  0.01612881
  0.02698788  0.01854187 -0.0229231  -0.03435128  0.00324616 -0.03218399
 -0.02219504 -0.04733948  0.02987177 -0.03991032 -0.01656803  0.06523717
 -0.00089099  0.04314077  0.00483948  0.041541    0.03202881 -0.04650088
  0.04359148  0.05137241  0.08792212 -0.04618868  0.07390659 -0.05648563
 -0.04602117  0.00370023 -0.06861848  0.0720872   0.08317295  0.04900444
  0.049115   -0.04006304 -0.00548147  0.01856698  0.07397155 -0.04068609
  0.00813338 -0.05191947 -0.102857   -0.05161855 -0.07994813  0.04970784
 -0.08930678 -0.00649526 -0.00475674 -0.05295987 -0.00274003  0.05497954
  0.02313608 -0.03573774 -0.0238196   0.02974536  0.00588099 -0.0177815
  0.04977529  0.06648789 -0.02259308  0.00444193  0.00562225 -0.09175745
  0.0046155  -0.02499436  0.02853595 -0.03088366 -0.03604237 -0.03852984
 -0.04194935 -0.0515839   0.08475912 -0.0363245   0.00661439 -0.00675294
 -0.03142671 -0.07429854  0.01594148  0.00412836 -0.

In [51]:
trainface_embedding.shape

(512,)

In [52]:
#saving trainface embedding in a file
from numpy import savez_compressed
np.savez_compressed("C:\\FaceRecognitionFiles\\puru_face_embedding.npz",trainface_embedding,"Puru")

In [5]:
#testing with other images
import cv2
import tensorflow as tf
from PIL import Image
from mtcnn.mtcnn import MTCNN
import numpy as np
import matplotlib.pyplot as plt
detector = MTCNN()
from keras_facenet import FaceNet
embedder = FaceNet()

In [6]:
#to load an image from filepath

In [46]:
faces = cv2.imread("C:\\FaceRecognitionFiles\\testpic2.jpg")

In [47]:
cv2.imshow('test image', faces)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
#to load image from camera
cap = cv2.VideoCapture(0)

In [53]:
for i in range(10):
    has_image, image = cap.read()
    if not has_image:
        print('No frames are captured')
    #frame = cv2.resize(frame,(160,160))
    
cv2.imshow('testimage',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
faces = image

In [55]:
faces_metadata = detector.detect_faces(faces)

2/2 [==============================] - 0s 256ms/step


In [56]:
print('number of faces = ',len(faces_metadata))

number of faces =  0


In [41]:
print(faces_metadata)

[]


In [12]:
x = int(faces_metadata[2]['box'][0])
y = int(faces_metadata[2]['box'][1])
w = int(faces_metadata[2]['box'][2])
h = int(faces_metadata[2]['box'][3])

detected_face = cv2.rectangle(faces, (x,y),(x+w,y+h), color=255, thickness=3) #see the detected face outlines
cv2.imshow('Detected face with rectangle',detected_face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#get list of faces
def get_faces(image, faces_metadata, required_size = (160,160)):
    faces = []
    for i in range(len(faces_metadata)):
        face_index=0
        x = int(faces_metadata[i]['box'][0])
        y = int(faces_metadata[i]['box'][1])
        w = int(faces_metadata[i]['box'][2])
        h = int(faces_metadata[i]['box'][3])
        
        face = image[y:y+h, x:x+w]
        face = Image.fromarray(face)
        face = face.resize(required_size)
        face = np.asarray(face)
        faces.append(face)
        
    return faces

In [14]:
facesdata = get_faces(faces, faces_metadata, required_size = (160,160))

In [15]:
print('number of faces = ', len(facesdata))

number of faces =  3


In [16]:
#get embedding data of all faces
def get_embedding_facenet(face_pixels):
    face_pixels = face_pixels.astype('float32')
    mean, std = face_pixels.mean(), face_pixels.std()
    face_pixels = (face_pixels - mean)/std
    #transform face into one smaple 
    samples = np.expand_dims(face_pixels, axis=0)
    #make prediction to get embedding
    embedding = embedder.model.predict(samples)
    return embedding[0]

In [17]:
face_embeddings = []
for i in range(len(facesdata)):
    face_embedding = get_embedding_facenet(facesdata[i])
    face_embeddings.append(face_embedding)

1/1 [==============================] - 0s 34ms/step


In [18]:
#loading my embedding
def load_numpy_faces(faces_dataset_numpy):
    from numpy import load
    data = load(faces_dataset_numpy)
    faces, labels = data['arr_0'], data['arr_1']
    return faces, labels


In [19]:
faces_dataset_numpy = 'C:\\FaceRecognitionFiles\\puru_face_embedding.npz'
puru_face_embedding, puru_name = load_numpy_faces(faces_dataset_numpy)

In [20]:
faces_distances = np.linalg.norm(face_embeddings - puru_face_embedding, axis=1)

In [21]:
faces_distances

array([0.7161484, 1.2717508, 1.1657768], dtype=float32)

In [22]:
print('face with closest distance is: ', np.argmin(faces_distances))

face with closest distance is:  0


In [23]:
print(facesdata[0])

[[[ 46  54  61]
  [ 54  62  69]
  [ 58  66  73]
  ...
  [ 85 100 109]
  [ 79  94 103]
  [ 83  99 111]]

 [[ 46  54  61]
  [ 52  60  67]
  [ 58  66  73]
  ...
  [ 84  99 108]
  [ 78  93 102]
  [ 80  96 108]]

 [[ 44  52  59]
  [ 48  56  63]
  [ 54  62  69]
  ...
  [ 87 102 111]
  [ 81  96 105]
  [ 82  98 110]]

 ...

 [[ 33  39  38]
  [ 35  41  40]
  [ 36  42  41]
  ...
  [185 180 171]
  [185 180 171]
  [189 182 173]]

 [[ 33  39  38]
  [ 33  39  38]
  [ 34  40  39]
  ...
  [183 178 169]
  [182 177 168]
  [189 182 173]]

 [[ 33  39  38]
  [ 32  38  37]
  [ 32  38  37]
  ...
  [184 179 170]
  [183 178 169]
  [189 182 173]]]


In [26]:
if(faces_distances[np.argmin(faces_distances)] < 1):
    cv2.imshow('Answer', facesdata[np.argmin(faces_distances)])
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print('Face not found')